Repository zilliztech/milvus-migration, pull requests merged in 2023-11, with the labels that each got.

#70 storage: impl local copy process record
  storage/copier.go
Labels: approved, lgtm, size/M

#71 storage: check file length after copy
  storage/copier.go
Labels: size/S, approved, lgtm

#72 storage: pass file size to minio
  storage/client.go
  storage/copier.go
  storage/minio.go
Labels: size/S, approved, lgtm

#74 add LICENSE to convert.go file
  core/transform/numpy/convert.go
Labels: size/XS, approved, lgtm
