Repository zilliztech/milvus-migration, pull requests merged in 2024-01, with the labels that each got.

#76 storage/azure: eat abort err
  storage/azure.go
Labels: size/XS, approved, lgtm

#78 storage: fix az abort err
  storage/azure.go
Labels: size/S, approved, lgtm

#77 storage: support io.readAt and io.Seek
  go.mod
  go.sum
  storage/aws.go
  storage/azure.go
  storage/client.go
  storage/copier.go
  storage/s3.go
  storage/s3_bigfile.go
Labels: approved, lgtm, size/XXL

#79 support tencent storage
  go.mod
  go.sum
  storage/aliyun.go
  storage/client.go
  storage/tencent.go
Labels: approved, lgtm, size/L
