Repository zilliztech/milvus-migration, pull requests merged in 2024-08, with the labels that each got.

#93 Modify the docker compose command
  .github/workflows/CI_es_milvus2x_main.yaml
  .github/workflows/CI_faiss_milvus2x_main.yaml
  .github/workflows/CI_milvus1x_milvus2x_main.yaml
  .github/workflows/CI_milvus1x_milvus2x_specify_config_main.yaml
  scripts/check_healthy.sh
Labels: size/S

#92 support specify Milvus database and upsert
  README.md
  README_2X.md
  README_ES.md
  core/common/constant.go
  core/config/config.go
  core/config/resolve.go
  core/dbclient/cus_field_milvus2x.go
  core/dbclient/milvus2x.go
  core/loader/cus_milvus2x_loader.go
  starter/migration/milvus2x_starter.go
  storage/milvus2x/milvus2_3_ver.go
Labels: approved, size/L

#97 Feature support batchCollection & DynamicFields migration
  cmd/root.go
  cmd/start.go
  core/common/constant.go
  core/data/process_info.go
  core/transform/milvus2x/convert/milvus2x_convert.go
  core/type/milvus2xtype/mlv2x_type.go
  go.mod
  go.sum
  server/function.go
  starter/starter.go
  storage/milvus2x/milvus2_3_ver.go
  testfiles/milvus2x/batch_collection_migration.sh
Labels: approved, size/L

#98 Support migrate description
  README_2X.md
  core/transform/milvus2x/convert/milvus2x_convert.go
Labels: approved

#100 modify get rowCount method
  storage/milvus2x/milvus2_3_ver.go
Labels: approved

#101 Feature support collection Disable <-> Enable AutoId migration
  README_2X.md
  core/config/resolve_meta.go
  core/dbclient/cus_field_milvus2x.go
  core/reader/source/milvus2x_source.go
  core/transform/milvus2x/convert/milvus2x_convert.go
  core/type/milvustype/type.go
  go.mod
  go.sum
  storage/milvus2x/milvus2_3_ver.go
Labels: approved

#102 support migration collection partions
  core/common/constant.go
  core/common/param.go
  core/dbclient/cus_field_milvus2x.go
  core/transform/milvus2x/convert/milvus2x_convert.go
  storage/milvus2x/base.go
  storage/milvus2x/milvus2_3_ver.go
Labels: approved, size/M

#103 migration data to origin partition
  core/data/process_info.go
  core/dbclient/cus_field_milvus2x.go
  core/dbclient/milvus2x.go
  core/dumper/mode_starter_milvus2x.go
  core/loader/cus_milvus2x_loader.go
  core/reader/source/milvus2x_source.go
  core/transform/milvus2x/convert/milvus2x_convert.go
  core/type/milvus2xtype/mlv2x_type.go
  storage/milvus2x/base.go
  storage/milvus2x/milvus2_3_ver.go
Labels: approved
